### ISSUE TITLE
Joystick Coin/Start/Fire aren't mapped correct

### ISSUE THREAD

**Issue by NML32** [MiSTer-devel/Arcade-Pooyan_MiSTer#1]
Even after re-mapping the Joypad the Coin/Start and Fire buttons don't seem to be mapped correctly.
After mapping the Joypad the below buttons seem to be incorrect.

P1 start/coin = Fire
P2 start/coin = P1 start/coin

I opened a ticket here because the Atari Forum appears to be having issues.

**Comment by sorgelig** [comment]
Fire button has been lost while copy/paste from previous core :)
fixed.
